#!/bin/sh

svn ci -m ""

#
cp -f helper/mute.php  opensim.modules/Messaging/php
cp -f helper/profile.php opensim.modules/Profile/php
cp -f helper/parser.php   opensim.modules/Search/php
cp -f helper/query.php    opensim.modules/Search/php
cp -f helper/register.php opensim.modules/Search/php

cp -f include/profile_config.php opensim.modules/Profile/php
cp -f include/search_config.php  opensim.modules/Search/php

#
(cd jbxl && svn ci -m "")
#(cd opensimwiredux && svn ci -m "")
(cd flotsam_XmlRpcGroup && svn ci -m "")
(cd opensim.phplib && svn ci -m "")
(cd opensim.modules && svn ci -m "")
(cd opensim.helper && svn ci -m "")
#(cd osprofile && svn ci -m "")
#(cd ossearch && svn ci -m "")
