#!/bin/sh

if [ $# -lt 1 ]; then
    echo Usage.... $0 Install_Directory_of_OpenSim 
    exit
fi

OS_DIR=$1
if [ ! -d $OS_DIR ]; then
    echo "not exist $OS_DIR that is installed OpenSim"
    exit
fi

cp -Rpd osprofile $OS_DIR
cp -pf opensim.phplib/cs_source/MuteListModule.cs $OS_DIR/OpenSim/Region/CoreModules/Avatar/InstantMessage/
cp -pf opensim.phplib/cs_source/OfflineMessageModule.cs $OS_DIR/OpenSim/Region/CoreModules/Avatar/InstantMessage/
